plugins {
    id 'com.android.application'
}

android {
    namespace '__APPID__'
    compileSdk 34

    defaultConfig {
        applicationId '__APPID__'
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName '0.1.0'

        externalNativeBuild {
            cmake {
                cFlags '-O3 -ffunction-sections -fdata-sections'
            }
        }
        ndk {
            abiFilters 'armeabi-v7a', 'arm64-v8a'
        }
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            minifyEnabled true
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    externalNativeBuild {
        cmake {
            path 'src/main/cpp/CMakeLists.txt'
            version '3.22.1'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
